# This is a config for E2B sandbox template.
# You can use template ID (64wj021ih6eokjzs38f7) or template name (webgor-nextjs-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("webgor-nextjs-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("webgor-nextjs-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('webgor-nextjs-test2')

team_id = "4c0c7826-80de-480a-847f-c0c1f15c7617"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "webgor-nextjs-test2"
template_id = "64wj021ih6eokjzs38f7"
